### ISSUE TITLE
Can i use this report package with Vue?

### ISSUE THREAD

**Issue by veekthoven** [Copyleaks/plagiarism-report#1]
Hello, my application frontend is built with Vue while the backend is built with PHP.  According to the instructions of this package, it is built on Angular. Can i still use it?

**Comment by elir-copyleaks** [comment]
Hi,

It's possible according to:
https://stackoverflow.com/questions/48691775/how-to-merge-angular-and-vue-projects-together
and
https://www.reddit.com/r/vuejs/comments/6y0k12/angularjs_1x_inside_a_vuejs_component/

You can use an iframe or the microservices mentioned in the stackoverflow answer above.
It would help to know your use case better. What are you planning to do with the report ( beside showing it in your page ). 

Thanks, Eli.

**Comment by veekthoven** [comment]
But I think you should release the documentation of the report javascript file (/v1/dist/copyleaks-plagiarism-report.min.js) so anybody can build his own front end around it instead of forcing us to use Angular. It would go a long way. We are building a plagiarism software for schools.

**Comment by elir-copyleaks** [comment]
Thank you for your idea. At the moment this is the only version supported. It is possible to use alongside other frameworks beside angularJs ( Either in the same page or in a different page on your site ).
