### ISSUE TITLE
error when running  npm install @copyleaks\plagiarism-report --save-dev

### ISSUE THREAD

**Issue by errakeshpd** [Copyleaks/plagiarism-report#2]
[root@server plagiarism-report]# npm install @copyleaks\plagiarism-report --save-dev
npm ERR! addLocal Could not install /home/website/RoR/plagiarism-report/@copyleaksplagiarism-report
npm ERR! Linux 2.6.32-042stab123.1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "@copyleaksplagiarism-report" "--save-dev"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! path /home/website/RoR/plagiarism-report/@copyleaksplagiarism-report
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/website/RoR/plagiarism-report/@copyleaksplagiarism-report'
npm ERR! enoent ENOENT: no such file or directory, open '/home/website/RoR/plagiarism-report/@copyleaksplagiarism-report'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /home/website/RoR/plagiarism-report/npm-debug.log

also I have noticed after running rpm install 
there is no  folder named `@copyleaks/plagiarism-report`.

**Comment by Copyleaks** [comment]
Add the file `package.json` to your project, with this cotent:

```
{
    "dependencies": {
        "@copyleaks/plagiarism-report": "1.0.35"
    }
}
```
Then, run this command:
```
cd your/project/path
npm install

```

Does it solve the problem?

**Comment by errakeshpd** [comment]
perfect! this works..
