### ISSUE TITLE
V3 api urls returning 404

### ISSUE THREAD

**Issue by veekthoven** [Copyleaks/plagiarism-report#3]
When I make a get request to http://api.copyleaks.com/v3/downloads/{scanId}, i get a 404 response.

But when i turn it to http://api.copyleaks.com/v2/downloads/{scanId}, it works just fine.

 What could be the issue?

**Comment by Copyleaks** [comment]
Hi, 
Most probably because the scan you about to download is created with the version 1 APIs. 
Mixing up the two version, old (v1) and new (v3), isn't possible. 

So, for old scan please use the v1 documentation - https://api.copyleaks.com/documentation/v1

I recommend you to upgrade your code to the newer version - V3. 

Let me know if it isn't solving your problem.

**Comment by veekthoven** [comment]
Please give me the link to the version 3 documentation.

And how can I upgrade my code to the V3? Are these things documented?

**Comment by veekthoven** [comment]
Also, the PHP SDK is using V2 by default. So how am i supposed to use v3 when the official SDK you guys provide is using v2

**Comment by veekthoven** [comment]
<img width="1417" alt="Screenshot 2019-06-04 at 12 02 53 PM" src="https://user-images.githubusercontent.com/32249717/58874391-9ef1cb80-86c0-11e9-9997-bbbd35617c75.png">
These are JUST the endpoints available for V3 documentation for education. Am i right?

**Comment by veekthoven** [comment]
Also, your [PHP SDK](https://github.com/Copyleaks/PHP-Plagiarism-Checker) by default uses V1. Is it not supposed to be using v3 since this is your current version?

**Comment by Copyleaks** [comment]
We do not have a PHP SDK available for V3 yet however we do offer [full documentation](https://api.copyleaks.com/documentation/v3) including examples in PHP for each one of the activities. 

You will just need to make sure to send to the right v3 endpoint and work with the right v3 names (for example "create-by" became 'submit' in V3).
