### ISSUE TITLE
error when running  "npm run demoV3" on centos

### ISSUE THREAD

**Issue by errakeshpd** [Copyleaks/plagiarism-report#4]
[root@server plagiarism-report]# npm run demoV3

> @copyleaks/plagiarism-report@1.0.35 demoV3 /myapp/plagiarism-report/node_modules/@copyleaks/plagiarism-report
> node ./hosts/v3/demoApp.js

/myapp/plagiarism-report/node_modules/@copyleaks/plagiarism-report/hosts/v3/demoApp.js:66
app.get('/download-pdf/v3', async function (req, res) {
                            ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 2.6.32-042stab123.1
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "demoV3"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @copyleaks/plagiarism-report@1.0.35 demoV3: `node ./hosts/v3/demoApp.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @copyleaks/plagiarism-report@1.0.35 demoV3 script 'node ./hosts/v3/demoApp.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @copyleaks/plagiarism-report package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./hosts/v3/demoApp.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @copyleaks/plagiarism-report
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @copyleaks/plagiarism-report
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /myapp/node_modules/@copyleaks/plagiarism-report/npm-debug.log

**Comment by errakeshpd** [comment]
node -v
v6.17.1

**Comment by Copyleaks** [comment]
Hi, 
As I said before, it may be a permissions problem. Make sure you have the right permission to open the requested port. By default, it's not hosting on port 80/443 so you may need to change this port or get enough permissions to do it. 

I recommend you to create a empty node project, just to make sure that the environment can handle this.

**Comment by Copyleaks** [comment]
Those logs are from the same issue like your other question?

**Comment by errakeshpd** [comment]
The previous one was in different platform(shared hosting) and this is on a centos VPS and it is different error than the previous

**Comment by errakeshpd** [comment]
It is showing like syntax mistake...

**Comment by doctsh** [comment]
I managed to resolve this by doing the following:
update nodejs and npm to the latest
and declare environment path as:
export PATH=/opt/cpanel/ea-nodejs10/bin/:$PATH
voila! it works now
but no reply from copyleaks! worried...this can put into consistent use?!

**Comment by Copyleaks** [comment]
Hello doctsh, 
Thanks for reporting that you solved the issue. 

The support on our sdk are limited because it's depending on multiple variables on client side (OS version, shared\not-shared, cloud, ...). We can't support all the configuration, but we can try. 
For that reason we share our SDKs as fully open source. In that way you can independently solve problems.
