### ISSUE TITLE
error when running "Run JS script" from shared hosting account....

### ISSUE THREAD

**Issue by errakeshpd** [Copyleaks/plagiarism-report#5]
returncode: 1
stdout:
> @copyleaks/plagiarism-report@1.0.35 demoV3 /home/raketfvv/repositories/plagiarism-report
> node ./hosts/v3/demoApp.js
stderr:
npm WARN lifecycle The node binary used for scripts is /home/raketfvv/nodevenv/repositories/plagiarism-report/9/bin/node but npm is using /opt/alt/alt-nodejs9/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3003
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at Server.listen (net.js:1475:7)
    at Function.listen (/home/raketfvv/nodevenv/repositories/plagiarism-report/9/lib/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/raketfvv/repositories/plagiarism-report/hosts/v3/demoApp.js:70:5)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1366:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:697:11)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @copyleaks/plagiarism-report@1.0.35 demoV3: `node ./hosts/v3/demoApp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @copyleaks/plagiarism-report@1.0.35 demoV3 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/raketfvv/.npm/_logs/2019-06-05T13_50_55_098Z-debug.log

**Comment by errakeshpd** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/opt/alt/alt-nodejs9/root/usr/bin/node',
1 verbose cli   '/opt/alt/alt-nodejs9/root/usr/bin/npm',
1 verbose cli   'run-script',
1 verbose cli   'demoV3',
1 verbose cli   '--' ]
2 info using npm@5.6.0
3 info using node@v9.11.2
4 verbose run-script [ 'predemoV3', 'demoV3', 'postdemoV3' ]
5 info lifecycle @copyleaks/plagiarism-report@1.0.35~predemoV3: @copyleaks/plagiarism-report@1.0.35
6 info lifecycle @copyleaks/plagiarism-report@1.0.35~demoV3: @copyleaks/plagiarism-report@1.0.35
7 warn lifecycle The node binary used for scripts is /home/raketfvv/nodevenv/repositories/plagiarism-report/9/bin/node but npm is using /opt/alt/alt-nodejs9/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle @copyleaks/plagiarism-report@1.0.35~demoV3: unsafe-perm in lifecycle true
9 verbose lifecycle @copyleaks/plagiarism-report@1.0.35~demoV3: PATH: /opt/alt/alt-nodejs9/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/raketfvv/repositories/plagiarism-report/node_modules/.bin:/home/raketfvv/nodevenv/repositories/plagiarism-report/9/bin:/opt/alt/alt-nodejs9/root/usr/bin:/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin
10 verbose lifecycle @copyleaks/plagiarism-report@1.0.35~demoV3: CWD: /home/raketfvv/repositories/plagiarism-report
11 silly lifecycle @copyleaks/plagiarism-report@1.0.35~demoV3: Args: [ '-c', 'node ./hosts/v3/demoApp.js' ]
12 silly lifecycle @copyleaks/plagiarism-report@1.0.35~demoV3: Returned: code: 1  signal: null
13 info lifecycle @copyleaks/plagiarism-report@1.0.35~demoV3: Failed to exec demoV3 script
14 verbose stack Error: @copyleaks/plagiarism-report@1.0.35 demoV3: `node ./hosts/v3/demoApp.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/opt/alt/alt-nodejs9/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:285:16)
14 verbose stack     at EventEmitter.emit (events.js:180:13)
14 verbose stack     at ChildProcess.<anonymous> (/opt/alt/alt-nodejs9/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:180:13)
14 verbose stack     at maybeClose (internal/child_process.js:936:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
15 verbose pkgid @copyleaks/plagiarism-report@1.0.35
16 verbose cwd /home/raketfvv/repositories/plagiarism-report
17 verbose Linux 2.6.32-954.3.5.lve1.4.59.el6.x86_64
18 verbose argv "/opt/alt/alt-nodejs9/root/usr/bin/node" "/opt/alt/alt-nodejs9/root/usr/bin/npm" "run-script" "demoV3" "--"
19 verbose node v9.11.2
20 verbose npm  v5.6.0
21 error code ELIFECYCLE
22 error errno 1
23 error @copyleaks/plagiarism-report@1.0.35 demoV3: `node ./hosts/v3/demoApp.js`
23 error Exit status 1
24 error Failed at the @copyleaks/plagiarism-report@1.0.35 demoV3 script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Copyleaks** [comment]
From the stack trace I see that the function `Server.listen` is failing. 

Are you sure that you have the right permissions to listen on this machine?
Does it working for you locally?

**Comment by errakeshpd** [comment]
yes, it is working local Mac machine...

when I tried in VPS and Shared Hosting accounts both failed both are different OS

**Comment by errakeshpd** [comment]
![Screenshot 2019-06-05 at 9 48 49 PM](https://user-images.githubusercontent.com/5379778/58972715-cab5a400-87db-11e9-8fd7-1f004b4d800d.png)

**Comment by Copyleaks** [comment]
Hi,
As I said before, it may be a permissions problem. Make sure you have the right permission to open the requested port. By default, it's not hosting on port 80/443 so you may need to change this port or get enough permissions to do it.

I recommend you to create a empty node project, just to make sure that the environment can handle this.

**Comment by Copyleaks** [comment]
Is this solution related to this thread?
https://github.com/Copyleaks/plagiarism-report/issues/4
