### ISSUE TITLE
copyleaksService.pushScanResult takes 1 argument not 2

### ISSUE THREAD

**Issue by mnelson4** [Copyleaks/plagiarism-report#55]
**Describe the bug**
The readme says to use code like this: 
```
.subscribe(scanResult => copyleaksService.pushScanResult(result.id, scanResult));
```

which results in errors like this:

```
Error: src/app/app.component.ts:43:79 - error TS2554: Expected 1 arguments, but got 2.

43           .subscribe(scanResult => copyleaksService.pushScanResult(result.id, scanResult));
```

I assume that's from the older version of Copyleaks Python code. 
Looking at the live demo, `copyleaksService.pushScanResult()` should instead accept an object with keys `id` and `result`, like so:

```
copyleaksService.pushScanResult({id:result.id, result:scanResult}))
```
Also, there's a bunch of imports needed (see the demo) to get it to work.

**To Reproduce**
Follow readme's instructions with Angular 8 and Copyleaks version 3.1.3.
Try to run `ng build` on an app using the component code suggested.

**Comment by CL-BayanAbuawad** [comment]
@mnelson4 thank you for your issue report, the issue was fixed and pushed.

if you're using angular 8, then you should use the report 2x+ version and not 3x+ as mentioned in the [installation section](https://github.com/Copyleaks/plagiarism-report#installation)
