### ISSUE TITLE
Need other language support

### ISSUE THREAD

**Issue by nakshatra-nahar** [Copyleaks/plagiarism-report#92]
Kindly Mention other language support to report please kindly add other language like hebrew

**Comment by CL-BayanAbuawad** [comment]
@nakshatra-nahar we do have support for translations, you can use the [translations service](https://github.com/Copyleaks/plagiarism-report/blob/6bc8fcd705fc98812e37a94002c94242188162a4/client/projects/plagiarism-report/src/lib/plagiarism-report/services/copyleaks-translate.service.ts#L4) to pass your own translations to it

`this.copyleaksTranslationsSvc.setTranslations({...});`
