### ISSUE TITLE
0910: Angular has detected that the `sandbox` was applied as a binding to an <iframe>

### ISSUE THREAD

**Issue by dhrcodeer** [Copyleaks/plagiarism-report#96]
**Describe the bug**
Both `OriginalComponent` and `SuspectComponent` throw an Angular NG0910 error (https://angular.io/errors/NG0910), breaking the iframes for rich text mode and source previews.

**To Reproduce**
1. Clone https://github.com/Copyleaks/plagiarism-report-demo
2. Run `npm install`
3. Run `npm start`

**Expected behavior**
Working iframes, just as on https://app.copyleaks.com/dashboard

**Desktop (please complete the following information):**
 - Angular 13
 - @copyleaks/plagiarism-report 4.1.21

**Comment by CL-BayanAbuawad** [comment]
@dhrcodeer a fix was deployed to both the report package and [demo](https://github.com/Copyleaks/plagiarism-report-demo).
